//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Hotel_Booking_Site.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Tbl_Calisan
    {
        public int CalisanID { get; set; }
        public string CalisanIsim { get; set; }
        public string CalisanSoyisim { get; set; }
        public string CalisanUyruk { get; set; }
        public string CalisanPozisyon { get; set; }
        public string CalisanMusait { get; set; }
    }
}
