//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Hotel_Booking_Site.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    public partial class UserProfile
    {
        public int UserID { get; set; }
        [Required(ErrorMessage = "Kullanýcý adýnýzý boþ veya yanlýþ girdiniz. Lütfen Tekrar giriniz.")]
        public string Username { get; set; }
        [Required(ErrorMessage = "Þifrenizi boþ veya yanlýþ girdiniz. Lütfen tekrar giriniz.")]
        [DataType(DataType.Password)]
        public string Password { get; set; }
    }
}
